-- begin DBCHS_HELPTEXT
alter table DBCHS_HELPTEXT add constraint FK_DBCHS_HELPTE_HELP_CONTEXT foreign key (HELP_CONTEXT_ID) references DBCHS_HELP_CONTEXT(ID)^
alter table DBCHS_HELPTEXT add constraint FK_DBCHS_HELPTEXT_CATEGORY foreign key (CATEGORY_ID) references DBCHS_HELPTEXT_CATEGORY(ID)^
create index IDX_DBCHS_HELPTE_HELP_CONTEXT on DBCHS_HELPTEXT (HELP_CONTEXT_ID)^
create index IDX_DBCHS_HELPTEXT_CATEGORY on DBCHS_HELPTEXT (CATEGORY_ID)^
-- end DBCHS_HELPTEXT
